### chamada GET para /clientes 
GET http://localhost:3000/api/v1/clientes
###
GET http://localhost:3000/api/v1/clientes/1
###
GET http://localhost:3000/api/v1/clientes/nome/Zezinho
###
POST http://localhost:3000/api/v1/clientes
Content-Type: application/json

{
    "nome": "Huguinho",
    "endereco": "rua lelele 300",
    "sexo": "Masculino",
    "telefone": "5555-4444"
}
###
PUT http://localhost:3000/api/v1/clientes/1
Content-Type: application/json

{
    "nome": "Zezinho da Silva",
    "endereco": "rua lalalala 500", 
    "sexo": "Masculino", 
    "telefone": "5555-6666"
}
###